<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/05/01 23:10:12

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=shptech.com;dbname=booking',
  'username' => 'booking',
  'password' => 123123,
  'name' => 'doctrine',
)),);
