<?php

/**
 * PluginArrangementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginArrangementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginArrangementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginArrangement');
    }
}