<?php

/**
 * PluginCompanyToArrangementTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCompanyToArrangementTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCompanyToArrangementTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCompanyToArrangement');
    }
}