<?php

/**
 * PluginBookingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginBookingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginBookingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginBooking');
    }
}