<?php

/**
 * BaseBooking
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property string $email
 * @property string $phone
 * @property integer $seats
 * @property timestamp $arrival
 * @property boolean $no_show
 * 
 * @method string    getFirstName()  Returns the current record's "first_name" value
 * @method string    getLastName()   Returns the current record's "last_name" value
 * @method string    getEmail()      Returns the current record's "email" value
 * @method string    getPhone()      Returns the current record's "phone" value
 * @method integer   getSeats()      Returns the current record's "seats" value
 * @method timestamp getArrival()    Returns the current record's "arrival" value
 * @method boolean   getNoShow()     Returns the current record's "no_show" value
 * @method Booking   setFirstName()  Sets the current record's "first_name" value
 * @method Booking   setLastName()   Sets the current record's "last_name" value
 * @method Booking   setEmail()      Sets the current record's "email" value
 * @method Booking   setPhone()      Sets the current record's "phone" value
 * @method Booking   setSeats()      Sets the current record's "seats" value
 * @method Booking   setArrival()    Sets the current record's "arrival" value
 * @method Booking   setNoShow()     Sets the current record's "no_show" value
 * 
 * @package    booking
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBooking extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('booking');
        $this->hasColumn('first_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('last_name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('email', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('seats', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('arrival', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('no_show', 'boolean', null, array(
             'type' => 'boolean',
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}