<?php

/**
 * BaseCompany
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Arrangements
 * @property Doctrine_Collection $CompanyToArrangement
 * 
 * @method string              getName()                 Returns the current record's "name" value
 * @method string              getDescription()          Returns the current record's "description" value
 * @method Doctrine_Collection getArrangements()         Returns the current record's "Arrangements" collection
 * @method Doctrine_Collection getCompanyToArrangement() Returns the current record's "CompanyToArrangement" collection
 * @method Company             setName()                 Sets the current record's "name" value
 * @method Company             setDescription()          Sets the current record's "description" value
 * @method Company             setArrangements()         Sets the current record's "Arrangements" collection
 * @method Company             setCompanyToArrangement() Sets the current record's "CompanyToArrangement" collection
 * 
 * @package    booking
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCompany extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('company');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Arrangement as Arrangements', array(
             'refClass' => 'CompanyToArrangement',
             'local' => 'company_id',
             'foreign' => 'table_id'));

        $this->hasMany('CompanyToArrangement', array(
             'local' => 'id',
             'foreign' => 'company_id'));
    }
}