<?php

/**
 * BaseArrangement
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $number
 * @property string $shape
 * @property integer $seats
 * @property string $x
 * @property string $y
 * @property string $length
 * @property string $width
 * @property Doctrine_Collection $Company
 * @property Doctrine_Collection $CompanyToArrangement
 * 
 * @method integer             getNumber()               Returns the current record's "number" value
 * @method string              getShape()                Returns the current record's "shape" value
 * @method integer             getSeats()                Returns the current record's "seats" value
 * @method string              getX()                    Returns the current record's "x" value
 * @method string              getY()                    Returns the current record's "y" value
 * @method string              getLength()               Returns the current record's "length" value
 * @method string              getWidth()                Returns the current record's "width" value
 * @method Doctrine_Collection getCompany()              Returns the current record's "Company" collection
 * @method Doctrine_Collection getCompanyToArrangement() Returns the current record's "CompanyToArrangement" collection
 * @method Arrangement         setNumber()               Sets the current record's "number" value
 * @method Arrangement         setShape()                Sets the current record's "shape" value
 * @method Arrangement         setSeats()                Sets the current record's "seats" value
 * @method Arrangement         setX()                    Sets the current record's "x" value
 * @method Arrangement         setY()                    Sets the current record's "y" value
 * @method Arrangement         setLength()               Sets the current record's "length" value
 * @method Arrangement         setWidth()                Sets the current record's "width" value
 * @method Arrangement         setCompany()              Sets the current record's "Company" collection
 * @method Arrangement         setCompanyToArrangement() Sets the current record's "CompanyToArrangement" collection
 * 
 * @package    booking
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseArrangement extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('arrangement');
        $this->hasColumn('number', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('shape', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('seats', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('x', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('y', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('length', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('width', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Company', array(
             'refClass' => 'CompanyToArrangement',
             'local' => 'table_id',
             'foreign' => 'company_id'));

        $this->hasMany('CompanyToArrangement', array(
             'local' => 'id',
             'foreign' => 'table_id'));
    }
}