<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/05/01 22:22:34
sfConfig::add(array(
  'mod_bookingfrontend_enabled' => true,
  'mod_bookingfrontend_view_class' => 'sfPHP',
));
