<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2010/05/01 21:56:52
sfConfig::add(array(
  'mod_bookingfrontend_enabled' => true,
  'mod_bookingfrontend_view_class' => 'sfPHP',
));
